### PR TITLE
fix(types): write options dryRun and partialSuccess (#711)

### LINKED ISSUE #711: Dry run support in Write API
I am trying to set dryRun flag of the [write api](https://cloud.google.com/logging/docs/reference/v2/rest/v2/entries/write). 

The `WriteOptions` interface does not support passing the dryRun boolean. Is there any other way to accomplish this?

### PR DESCRIPTION
**Pull request by zamnuts**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [X] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/nodejs-logging/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [X] Ensure the tests and linter pass
- [X] Code coverage does not decrease (if any source code was changed)
- [X] Appropriate docs were updated (if necessary)

Fixes #711 🦕

### CODE REVIEW

**Comment by zamnuts** [comment]
@googlebot I signed it!

File: src/log.ts [hunk 1]
```diff
@@ -55,8 +55,10 @@ export type DeleteCallback = ApiResponseCallback;
 
 export type MonitoredResource = google.api.IMonitoredResource;
 export interface WriteOptions {
+  dryRun?: boolean;
   gaxOptions?: CallOptions;
   labels?: {[index: string]: string};
+  partialSuccess?: boolean;
```
Comment (stephenplusplus) [inline src/log.ts]: Nice finding this one as well :)

File: src/log.ts [hunk 2]
```diff
@@ -721,9 +723,14 @@ class Log implements LogSeverityFunctions {
    * Write options.
    *
    * @typedef {object} WriteOptions
+   * @property {boolean} [dryRun] If true, the request should expect normal
+   *     response, but the entries won't be persisted nor exported.
    * @property {object} gaxOptions Request configuration options, outlined here:
    *     https://googleapis.github.io/gax-nodejs/global.html#CallOptions.
    * @property {object[]} labels Labels to set on the log.
+   * @property {boolean} [partialSuccess] Whether valid entries should be
```
Comment (stephenplusplus) [inline src/log.ts]: I always appreciate alphabetizing.
